services:
  meme-php:
    container_name: meme-php
    build:
      dockerfile: containers/Dockerfile
      args:
        USER_ID: 1000
        GROUP_ID: 1000
        USER_NAME: unit
    volumes:
      - ./:/var/www
      - ./containers/configs/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./containers/configs/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./containers/configs/unit/unit.json:/docker-entrypoint.d/unit.json:ro
    ports:
      - '4205:80'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.meme-cloud.rule=Host(`meme-cloud.devilops.tech`)"
      - "traefik.http.routers.meme-cloud.entrypoints=websecure"
      - "traefik.http.routers.meme-cloud.tls.certresolver=letsencrypt"
      - "traefik.http.services.meme-cloud.loadbalancer.server.port=80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - infra_traefik_net
      - meme-cloud

  meme-db:
    container_name: meme-db
    build:
      dockerfile: containers/percona.Dockerfile
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    environment:
      MYSQL_USER: alex
      MYSQL_PASSWORD: 1
      MYSQL_DATABASE: meme
      MYSQL_ROOT_PASSWORD: 1
    ports:
      - '4206:3306'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./containers/init-scripts/percona-init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./var/data/percona:/var/lib/mysql
      - ./var/logs/percona:/var/log/mysql
      - /etc/localtime:/etc/localtime:ro
    networks:
      - meme-cloud

networks:
  infra_traefik_net:
    external: true
  meme-cloud:
    internal: true