services:
  meme-php:
    container_name: meme-php
    build:
      dockerfile: containers/Dockerfile
      args:
        USER_ID: 1000
        GROUP_ID: 1000
        USER_NAME: unit
    volumes:
      - ./:/var/www
      - ./containers/configs/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./containers/configs/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./containers/configs/unit/unit.json:/docker-entrypoint.d/unit.json:ro
    ports:
      - '8000:80'
    extra_hosts:
      - "host.docker.internal:host-gateway"

  meme-node:
    container_name: meme-node
    image: node:24-alpine3.21
    user: 1000:1000
    volumes:
      - ./:/var/www
    working_dir: /var/www
    ports:
      - '5173:5173'
    command: >
      sh -c "npm run dev ---host 0.0.0.0"

  meme-db:
    container_name: meme-db
    build:
      dockerfile: containers/percona.Dockerfile
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    environment:
      MYSQL_USER: alex
      MYSQL_PASSWORD: 1
      MYSQL_DATABASE: meme
      MYSQL_ROOT_PASSWORD: 1
    ports:
      - 3306:3306
    volumes:
      - ./containers/init-scripts/percona-init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./var/data/percona:/var/lib/mysql
      - ./var/logs/percona:/var/log/mysql
      - /etc/localtime:/etc/localtime:ro

  meme-minio:
    container_name: meme-minio
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: alex
      MINIO_ROOT_PASSWORD: Miha1000
    ports:
      - '9001:9001'
    volumes:
      - ./var/data/minio:/data

  meme-storybook:
    container_name: meme-storybook
    image: node:24-alpine3.21
    working_dir: /var/www
    user: 1000:1000
    volumes:
      - ./:/var/www
    ports:
      - "6006:6006"
    command: >
      sh -c "npm install && npm run storybook -- --no-open"

